default: &default
  adapter: postgresql
  encoding: unicode
  database: shop_laptop
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: 123456

development:
  <<: *default
  database: shop_laptop_development

test:
  <<: *default
  database: shop_laptop_test

production:
  <<: *default
  database: shop_laptop_production
