default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin_helper_user
  password: 123

development:
  <<: *default
  database: db/shop_laptop_development

test:
  <<: *default
  database: db/shop_laptop_test

production:
  <<: *default
  database: db/shop_laptop_production
