user:
  sessions:
    - create
  password:
    - create
    - validate_token
    - update
  users:
    - create
    - update
    - update_password
    - show
  categories:
    - show
  products:
    - show
  order_items:
    - show
    - create
    - index
    - update
    - update_quantity
    - destroy
  orders:
    - show
    - create
    - cancel
  carts:
    - show
    - customer_index
admin:
  users:
    - index
    - destroy
  categories:
    - create
    - index
    - update
    - destroy
  products:
    - create
    - index
    - update
    - destroy
  order_items:
    - index
  orders:
    - index
    - done
    - approve
    - deny
  carts:
    - index