user:
  sessions:
    - create
  password:
    - create
    - validate_token
    - update
  users:
    - create
    - update
    - update_password
    - show
  categories:
    - show
  products:
    - show
    - index
  order_items:
    - show
    - create
    - index
    - update
    - update_quantity
    - destroy
  orders:
    - show
    - create
    - cancel
    - customer_index
  carts:
    - show
    - customer_show
admin:
  users:
    - index
    - destroy
  categories:
    - create
    - index
    - update
    - destroy
    - add_products
  products:
    - create
    - update
    - destroy
  order_items:
    - index
  orders:
    - index
    - done
    - approve
    - deny
  carts:
    - index
  statistics:
    - count_users
    - count_orders
    - count_revenue